//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCarros2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DSII_SuperCarrosEntities2 : DbContext
    {
        public DSII_SuperCarrosEntities2()
            : base("name=DSII_SuperCarrosEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Vehiculos> Vehiculos { get; set; }
    }
}
