//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCarros2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        public string Id { get; set; }
        public string Brand_Id { get; set; }
        public string ModeI_Id { get; set; }
        public string Color_Id { get; set; }
        public decimal Precio { get; set; }
        public string Combustible { get; set; }
        public string Type_Id { get; set; }
        public int Puertas { get; set; }
        public int Pasajeros { get; set; }
        public string Motor { get; set; }
        public string Transmisión { get; set; }
        public int Año { get; set; }
        public string Imagen { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Color Color { get; set; }
        public virtual Model Model { get; set; }
        public virtual Type Type { get; set; }
    }
}
